create table empregado(
	codigo	int,
	nome	varchar(60) not null,
	cpf		varchar(14) not null,
	sexo	char(1),
	datanasc date,
	logradouro varchar(50),
	nro		int,
	salario	numeric(8, 2) not null,
	depto_num	int,
	codigo_ger	int,
	constraint empregado_pk primary key(codigo),
	constraint emp_sal_ck check(salario > 0),
	constraint emp_sexo_ck check(sexo in ('M', 'F'))
);

create table departamento(
	numero		int,
	nome		varchar(20) not null,
	codigo_ger	int,
	data_inicio_ger	date,
	constraint	departamento_pk primary key(numero),
	constraint	depto_nome_uk unique(nome)
);

alter table departamento add constraint depto_ger_fk
	foreign key(codigo_ger) references empregado(codigo);

alter table empregado add constraint depto_num_fk
	foreign key(depto_num) references departamento(numero);

alter table empregado add constraint codigo_ger_fk
	foreign key(codigo_ger) references empregado(codigo);

-- ALTER TABLE
-- Adicionar colunas
alter table empregado add fone varchar(20);

-- Modificar colunas
alter table empregado alter fone type varchar(16);
-- alter table empregado modify fone varchar(16);

-- Renomear colunas
alter table empregado rename fone to fone_emp;

-- Apagar colunas
alter table empregado drop fone_emp;

-- Renomear constraints
alter table empregado rename constraint codigo_ger_fk to emp_gerente_fk;

-- Renomear tabelas
alter table empregado rename to emp;
alter table emp rename to empregado;

-- Apagar constraints
alter table empregado drop constraint emp_gerente_fk;

-- Alterar colunas para not null / null
alter table empregado alter depto_num set not null;
alter table empregado alter depto_num drop not null;

-- Colocar valor default para colunas
alter table empregado alter depto_num set default 10;
alter table empregado alter depto_num drop default;

-- Utilizando colunas auto incrementáveis
create table teste(
	id	serial primary key,
	descricao varchar(20)
);

-- Formas alternativas com GENERATED
create table aluno(
	id int generated always as identity,
	nome varchar(100),
	primary key(id)
);

create table aluno2(
	id int generated by default as identity,
	nome varchar(100),
	primary key(id)
);

-- Generated Columns
create table produto(
	id			serial primary key,
	descricao 	varchar(80),
	preco		numeric(10,2),
	quantidade	int,
	valor_total	numeric(10,2) generated always as (preco * quantidade) stored
);

-- Só funciona a partir da versão 18
create table produto2(
	id			serial primary key,
	descricao 	varchar(80),
	preco		numeric(10,2),
	quantidade	int,
	valor_total	numeric(10,2) generated always as (preco * quantidade) virtual
);

-- Apagar tabela
drop table departamento;
drop table empregado;

alter table aluno add id_responsavel int;
alter table aluno add foreign key(id_responsavel)
	references empregado(codigo);

alter table aluno drop constraint aluno_id_responsavel_fkey;
alter table departamento drop constraint depto_ger_fk;

drop table empregado;
drop table departamento;

-- Apagar tabelas em cascata
drop table departamento cascade;

-- Apagar base
drop database aula;

-- Criar base
create database aula;